name: Tests

on: [push]

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Process Manager for Node.js
      run: |
        set -x
        npm install -g pm2
    - name: Install dependencies
      run: |
        set -x
        npm install
    - name: Start JSON Server
      run: pm2 start ./node_modules/.bin/json-server -- ./test/integration/db.json
    
    - name: Run tests
      run: npm test
      
    - name: Stop JSON Server
      run: pm2 stop all

    - name: Start App
      run: pm2 start npm start
      
    - name: Start Cypress
      run: npm cy:run
      
    - name: Stop App
      run: pm2 stop all